### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grothjef/helper_methods#1]
It looks like the hidden `.rspec` file in this project is missing - probably due to copying and pasting the contents of this folder in Finder or another file manager. This would cause the specs to crash when you try to run them. You can get around this by manually entering the configuration when you run the specs like this:

```
bundle exec rspec --require spec_helper --format documentation --color
```

These are the failures I'm seeing:

```
Failures:

  1) MethodsPracticeHelpers#bootstrap_alert when passed both a message and a type div tag contains exactly 2 elements
     Failure/Error: expect( @alert.children.size ).to eq(2)

       expected: 2
            got: 3

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/bootstrap_alert_spec.rb:75:in `block (5 levels) in <top (required)>'

  2) MethodsPracticeHelpers#bootstrap_alert when passed both a message and a type div tag class attribute includes "alert-TYPE"
     Failure/Error: expect( @class_attr.value.include?("alert-#{@type}") ).to eq(true)

       expected: true
            got: false

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/bootstrap_alert_spec.rb:53:in `block (6 levels) in <top (required)>'

  3) MethodsPracticeHelpers#bootstrap_alert when passed only a message div tag class attribute includes "alert-info"
     Failure/Error: @contents = html_of bootstrap_alert(@message)
     ArgumentError:
       wrong number of arguments (1 for 2..3)
     # ./helpers/methods_practice_helpers.rb:10:in `bootstrap_alert'
     # ./spec/helpers/methods_practice_helpers/bootstrap_alert_spec.rb:213:in `block (4 levels) in <top (required)>'
```

See if you can resolve those, so that the Bootstrap alert acts as expected in the specifications. When you get 0 failures after running `bundle exec rspec --require spec_helper --format documentation --color`, the program is definitely working the way the hypothetical front-end devs are expecting.

If you get stuck, don't hesitate to let me know and I'll be happy to point you in the right direction. As I mentioned in our email, you have until the end of the day Friday to get everything fixed here, so you can focus on other projects today if you need to.

**Comment by grothjef** [comment]
Should be fixed now

**Comment by chrisvfritz** [comment]
:+1: Excellent!
